### PR TITLE
Rebuild python312 0 1 haa1add

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #22, closes #25  

This does a bit of housekeeping and adds myself to the maintainers. The housekeeping in detail is:
- Move to use pip
- Add stdlib jinja
- Add versioneer dependency (upstream really uses versioneer in non-vendored mode, even though the file is still included)

This makes things work for Python 3.12 (which removed `configparser.SafeConfigParser` which had been deprecated since Python 3.2 thereby breaking the very old vendored version of versioneer) and hopefully unblocks the rest of the outstanding PRs.

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
This is ready for review, @conda-forge/crick. If you prefer I don't become a maintainer, feel free to remove me.

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Comment by zklaus** [comment]
@jrbourbeau, I just noticed that you were not added as a reviewer because you were not in the `CODEOWNERS` file. This happened because there was no rerender in #18, and so you were added kind-of incompletely. Any rerender after that would have fixed it, but nothing was merged since.

Regardless, with this PR, that will be fixed too, and so here I am pinging you individually.

**Comment by stephenpardy** [comment]
@jrbourbeau just another ping to say that I am also interested in seeing this version in conda. Really appreciate your time here.

**Comment by zklaus** [comment]
@jcrist, looks like currently you are the only active maintainer, could you please have a look?

@conda-forge-admin, please rerender (due to this PR being open for some time now)

**Comment by MuellerSeb** [comment]
Afterwards we could go on to v0.0.6 and deal with numpy 2 support. For adding more eyes, I would also volunteer as maintainer (one conda package more won't make much of a difference now...)

**Pull request merged**
