### PR TITLE
Add ``@jrbourbeau`` as a maintainer

### PR DESCRIPTION
**Pull request by jrbourbeau**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

cc @jcrist whenever you get a moment

### CODE REVIEW

**Review by jcrist — APPROVED** [review]
Sorry for missing this!

**Comment by jrbourbeau** [comment]
@jcrist no problem -- could you merge this when you get a moment?

**Comment by dankerrigan** [comment]
We're interested in an updated conda release. Thanks for all your work on crick so far, @jcrist!

**Comment by jcrist** [comment]
Apologies for not merging this earlier, I saw the CI failures and thought it might not be mergeable (turns out it should be fine). Merging!

**Pull request merged**
